name: N1内核打包

on:
  repository_dispatch:
  workflow_dispatch:

  #schedule:
    #- cron: 0 16 * * 4

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  # FEEDS_CONF: N1/N1-my-feeds.conf.default
  # CONFIG_FILE: N1/N1-my.config
  # DIY_P1_SH: diy-part1.sh
  # DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 打包内核
      uses: unifreq/openwrt_packit@master
      env:
        WHOAMI: ham
        OPENWRT_ARMVIRT: https://github.com/woni928/OpenWRT/releases/download/02.17.0927_N1-flippy%E5%86%85%E6%A0%B8/openwrt-armvirt-64-default-rootfs.tar.gz
        PACKAGE_SOC: s905d
        KERNEL_AUTO_LATEST: true
       # KERNEL_REPO_URL: https://github.com/ham0223/OpenWRT-N1/tree/main/opt
        KERNEL_VERSION_NAME: 5.4.231
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: 发布固件
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.PACKAGED_OUTPUTDATE }}_N1-OpenWrt
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          测试打包
          
          
    - name: 清理Actions空间
      uses: Mattraks/delete-workflow-runs@main
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_days: 7
          #retain_days: ${{ github.event.inputs.action_days }}
          
